import Foundation
import Testing
@testable import MintoCore

@Suite("SpeakerLabelEditing")
struct SpeakerLabelEditingTests {
    @Test("labels: 빈 segment 배열은 빈 결과를 반환한다")
    func labelsReturnsEmptyForEmptySegments() {
        #expect(SpeakerLabelEditing.labels(in: []) == [])
    }

    @Test("labels: nil과 빈 speaker를 제외하고 중복 라벨은 첫 등장 순서만 남긴다")
    func labelsNormalizeDeduplicateAndPreserveFirstAppearanceOrder() {
        let segments = [
            segment("nil speaker", speaker: nil),
            segment("first", speaker: " 화자 1 "),
            segment("blank", speaker: " "),
            segment("second", speaker: "화자 2"),
            segment("duplicate", speaker: "화자 1"),
            segment("third", speaker: "\n화자 3\t"),
        ]

        #expect(SpeakerLabelEditing.labels(in: segments) == ["화자 1", "화자 2", "화자 3"])
    }

    @Test("isAutoGenerated: 자동 생성 화자 라벨만 true를 반환한다")
    func isAutoGeneratedDetectsGeneratedSpeakerLabels() {
        #expect(SpeakerLabel.isAutoGenerated("화자 1"))
        #expect(SpeakerLabel.isAutoGenerated("화자 12"))
        #expect(SpeakerLabel.isAutoGenerated(" 화자 1 "))
        #expect(!SpeakerLabel.isAutoGenerated("화자"))
        #expect(!SpeakerLabel.isAutoGenerated("화자 A"))
        #expect(!SpeakerLabel.isAutoGenerated("김철수"))
        #expect(!SpeakerLabel.isAutoGenerated(nil))
        #expect(!SpeakerLabel.isAutoGenerated(" "))
    }

    @Test("replacingSpeaker: source speaker 전체를 target으로 치환한다")
    func replacingSpeakerUpdatesEveryMatchingSegment() {
        let segments = [
            segment("a", speaker: "화자 1"),
            segment("b", speaker: "화자 2"),
            segment("c", speaker: "화자 1"),
            segment("d", speaker: nil),
        ]

        let updated = SpeakerLabelEditing.replacingSpeaker("화자 1", with: "PM", in: segments)

        #expect(updated.map(\.speaker) == ["PM", "화자 2", "PM", nil])
        #expect(updated.map(\.id) == segments.map(\.id))
    }

    @Test("replacingSpeaker: 매칭 없는 source는 원본을 유지한다")
    func replacingSpeakerKeepsSegmentsWhenSourceDoesNotMatch() {
        let segments = [
            segment("a", speaker: "화자 1"),
            segment("b", speaker: nil),
        ]

        let updated = SpeakerLabelEditing.replacingSpeaker("화자 3", with: "PM", in: segments)

        #expect(updated == segments)
    }

    @Test("replacingSpeaker: source와 target 라벨 공백은 정규화해서 비교하고 저장한다")
    func replacingSpeakerNormalizesSourceAndTargetWhitespace() {
        let segments = [
            segment("a", speaker: " 화자 1\n"),
            segment("b", speaker: "화자 1"),
            segment("c", speaker: "화자 2"),
        ]

        let updated = SpeakerLabelEditing.replacingSpeaker("  화자 1 ", with: "\tPM\n", in: segments)

        #expect(updated.map(\.speaker) == ["PM", "PM", "화자 2"])
    }

    @Test("replacingSpeaker: source와 target이 같으면 원본을 유지한다")
    func replacingSpeakerKeepsSegmentsWhenSourceAndTargetAreSame() {
        let segments = [
            segment("a", speaker: " 화자 1 "),
            segment("b", speaker: "화자 2"),
        ]

        let updated = SpeakerLabelEditing.replacingSpeaker("화자 1", with: " 화자 1 ", in: segments)

        #expect(updated == segments)
    }

    @Test("replacingSpeakerLabel: target이 없으면 source 라벨만 target으로 변경하고 임베딩은 보존한다")
    func replacingSpeakerLabelRenamesSourceEmbeddingWhenTargetDoesNotExist() throws {
        let embeddings = [
            speakerEmbedding("화자 1", embedding: [1, 0], embeddingModelID: "speaker-v1", dimensions: 7),
            speakerEmbedding("화자 2", embedding: [0, 1], embeddingModelID: "speaker-v1")
        ]

        let updated = try #require(
            SpeakerLabelEditing.replacingSpeakerLabel("화자 1", with: "PM", in: embeddings)
        )

        #expect(updated.map(\.speakerLabel) == ["PM", "화자 2"])
        #expect(updated[0].embedding == [1, 0])
        #expect(updated[0].embeddingModelID == "speaker-v1")
        #expect(updated[0].dimensions == 7)
        #expect(updated[1] == embeddings[1])
    }

    @Test("replacingSpeakerLabel: target이 있으면 source 항목을 제거하고 target 항목을 유지한다")
    func replacingSpeakerLabelMergesByKeepingTargetEmbedding() throws {
        let source = speakerEmbedding("화자 1", embedding: [1, 0], embeddingModelID: "speaker-v1")
        let target = speakerEmbedding("PM", embedding: [0, 1], embeddingModelID: "speaker-v1")
        let other = speakerEmbedding("화자 3", embedding: [0.5, 0.5], embeddingModelID: "speaker-v1")
        let embeddings = [source, target, other]

        let updated = try #require(
            SpeakerLabelEditing.replacingSpeakerLabel("화자 1", with: "PM", in: embeddings)
        )

        #expect(updated == [target, other])
        #expect(updated.count == embeddings.count - 1)
        #expect(!updated.contains(source))
    }

    @Test("replacingSpeakerLabel: nil 입력은 nil을 반환한다")
    func replacingSpeakerLabelReturnsNilForNilEmbeddings() {
        let updated = SpeakerLabelEditing.replacingSpeakerLabel(
            "화자 1",
            with: "PM",
            in: nil
        )

        #expect(updated == nil)
    }

    @Test("replacingSpeakerLabel: source와 target이 같거나 정규화에 실패하면 원본을 유지한다")
    func replacingSpeakerLabelKeepsEmbeddingsForNoopInputs() {
        let embeddings = [
            speakerEmbedding("화자 1", embedding: [1, 0], embeddingModelID: "speaker-v1"),
            speakerEmbedding("화자 2", embedding: [0, 1], embeddingModelID: "speaker-v1")
        ]

        let sameLabel = SpeakerLabelEditing.replacingSpeakerLabel("화자 1", with: " 화자 1 ", in: embeddings)
        let blankSource = SpeakerLabelEditing.replacingSpeakerLabel(" ", with: "PM", in: embeddings)
        let blankTarget = SpeakerLabelEditing.replacingSpeakerLabel("화자 1", with: " \n", in: embeddings)

        #expect(sameLabel == embeddings)
        #expect(blankSource == embeddings)
        #expect(blankTarget == embeddings)
    }

    @Test("replacingSpeakerLabel: source 라벨이 없으면 원본을 유지한다")
    func replacingSpeakerLabelKeepsEmbeddingsWhenSourceDoesNotMatch() {
        let embeddings = [
            speakerEmbedding("화자 1", embedding: [1, 0], embeddingModelID: "speaker-v1"),
            speakerEmbedding("화자 2", embedding: [0, 1], embeddingModelID: "speaker-v1")
        ]

        let updated = SpeakerLabelEditing.replacingSpeakerLabel("화자 3", with: "PM", in: embeddings)

        #expect(updated == embeddings)
    }

    @Test("reassignSegment: 지정 구간 하나만 target speaker로 변경한다")
    func reassignSegmentUpdatesOnlyMatchingSegment() {
        let targetID = Segment.ID()
        let segments = [
            segment("a", speaker: "화자 1"),
            segment("b", speaker: "화자 2", id: targetID),
            segment("c", speaker: "화자 3"),
        ]

        let updated = SpeakerLabelEditing.reassignSegment(id: targetID, to: "PM", in: segments)

        #expect(updated.map(\.speaker) == ["화자 1", "PM", "화자 3"])
        #expect(updated[0] == segments[0])
        #expect(updated[2] == segments[2])
    }

    @Test("reassignSegment: 없는 id는 원본을 유지한다")
    func reassignSegmentKeepsSegmentsWhenIDDoesNotMatch() {
        let segments = [
            segment("a", speaker: "화자 1"),
            segment("b", speaker: "화자 2"),
        ]

        let updated = SpeakerLabelEditing.reassignSegment(id: Segment.ID(), to: "PM", in: segments)

        #expect(updated == segments)
    }

    @Test("reassignSegment: 빈 target 라벨은 원본을 유지한다")
    func reassignSegmentKeepsSegmentsWhenTargetLabelIsBlank() {
        let targetID = Segment.ID()
        let segments = [
            segment("a", speaker: "화자 1", id: targetID),
            segment("b", speaker: "화자 2"),
        ]

        let updated = SpeakerLabelEditing.reassignSegment(id: targetID, to: " \n\t", in: segments)

        #expect(updated == segments)
    }

    @Test("reassignSegment: target 라벨 공백을 정규화해서 저장한다")
    func reassignSegmentNormalizesTargetWhitespace() {
        let targetID = Segment.ID()
        let segments = [
            segment("a", speaker: "화자 1", id: targetID),
            segment("b", speaker: "화자 2"),
        ]

        let updated = SpeakerLabelEditing.reassignSegment(id: targetID, to: "\tPM\n", in: segments)

        #expect(updated.map(\.speaker) == ["PM", "화자 2"])
    }

    @Test("nextNewSpeakerLabel: 기존 라벨이 없으면 화자 1을 반환한다")
    func nextNewSpeakerLabelReturnsFirstSpeakerForEmptyLabels() {
        #expect(SpeakerLabelEditing.nextNewSpeakerLabel(existing: []) == "화자 1")
    }

    @Test("nextNewSpeakerLabel: 사용 중인 화자 번호 다음 최소 번호를 반환한다")
    func nextNewSpeakerLabelReturnsSmallestUnusedSpeakerNumber() {
        #expect(SpeakerLabelEditing.nextNewSpeakerLabel(existing: ["화자 1"]) == "화자 2")
        #expect(SpeakerLabelEditing.nextNewSpeakerLabel(existing: ["화자 1", "화자 3"]) == "화자 2")
    }

    @Test("nextNewSpeakerLabel: 임의 라벨과 겹치지 않는 화자 라벨을 반환한다")
    func nextNewSpeakerLabelAvoidsCollisionWithArbitraryLabels() {
        #expect(SpeakerLabelEditing.nextNewSpeakerLabel(existing: ["A", "화자 1", "화자 2"]) == "화자 3")
    }

    private func segment(_ text: String, speaker: String?, id: Segment.ID = Segment.ID()) -> Segment {
        Segment(
            id: id,
            text: text,
            timestamp: Date(timeIntervalSinceReferenceDate: 0),
            duration: 1,
            speaker: speaker
        )
    }

    private func speakerEmbedding(
        _ speakerLabel: String,
        embedding: [Float],
        embeddingModelID: String,
        dimensions: Int? = nil
    ) -> MeetingRecord.MeetingSpeakerEmbedding {
        MeetingRecord.MeetingSpeakerEmbedding(
            speakerLabel: speakerLabel,
            embedding: embedding,
            embeddingModelID: embeddingModelID,
            dimensions: dimensions
        )
    }
}
