import Foundation

/// 전사 줄 화자 라벨 정규화. 공백뿐이거나 빈 라벨은 nil로 취급해 표시하지 않는다.
/// 전사 렌더 뷰 3곳(overlay/library/summary)이 같은 규칙을 쓰도록 단일 출처로 둔다.
enum SpeakerLabel {
    static func normalized(_ speaker: String?) -> String? {
        guard let trimmed = speaker?.trimmingCharacters(in: .whitespacesAndNewlines),
              !trimmed.isEmpty else {
            return nil
        }
        return trimmed
    }

    static func isAutoGenerated(_ label: String?) -> Bool {
        guard let label = normalized(label) else {
            return false
        }
        // DiarizationSpeakerLabeling.makeLabelMap / SpeakerLabelEditing.nextNewSpeakerLabel이
        // 만드는 "화자 \(n)" 자동 라벨을 보이스프린트 이름으로 등록하면 전역 저장소가
        // 오염되고 향후 오식별되므로 차단한다.
        return label.range(of: #"^화자 \d+$"#, options: .regularExpression) != nil
    }
}

enum SpeakerLabelEditing {
    static func labels(in segments: [Segment]) -> [String] {
        var seen = Set<String>()
        var labels: [String] = []
        for segment in segments {
            guard let label = SpeakerLabel.normalized(segment.speaker),
                  !seen.contains(label) else {
                continue
            }
            seen.insert(label)
            labels.append(label)
        }
        return labels
    }

    static func replacingSpeaker(
        _ source: String,
        with target: String,
        in segments: [Segment]
    ) -> [Segment] {
        guard let sourceLabel = SpeakerLabel.normalized(source),
              let targetLabel = SpeakerLabel.normalized(target),
              sourceLabel != targetLabel else {
            return segments
        }

        return segments.map { segment in
            guard SpeakerLabel.normalized(segment.speaker) == sourceLabel else {
                return segment
            }
            var updated = segment
            updated.speaker = targetLabel
            return updated
        }
    }

    static func replacingSpeakerLabel(
        _ source: String,
        with target: String,
        in embeddings: [MeetingRecord.MeetingSpeakerEmbedding]?
    ) -> [MeetingRecord.MeetingSpeakerEmbedding]? {
        guard let embeddings else {
            return nil
        }
        guard let sourceLabel = SpeakerLabel.normalized(source),
              let targetLabel = SpeakerLabel.normalized(target),
              sourceLabel != targetLabel else {
            return embeddings
        }
        guard embeddings.contains(where: { SpeakerLabel.normalized($0.speakerLabel) == sourceLabel }) else {
            return embeddings
        }

        let targetExists = embeddings.contains {
            SpeakerLabel.normalized($0.speakerLabel) == targetLabel
        }
        if targetExists {
            // 병합 시 target의 보이스프린트 샘플을 유지(평균 미적용)한다.
            // 정확한 가중평균은 항목별 sampleCount가 필요한데 현재 미보관이라, 예측 가능하게 target 샘플을 유지한다.
            return embeddings.filter {
                SpeakerLabel.normalized($0.speakerLabel) != sourceLabel
            }
        }

        return embeddings.map { entry in
            guard SpeakerLabel.normalized(entry.speakerLabel) == sourceLabel else {
                return entry
            }
            return MeetingRecord.MeetingSpeakerEmbedding(
                speakerLabel: targetLabel,
                embedding: entry.embedding,
                embeddingModelID: entry.embeddingModelID,
                dimensions: entry.dimensions
            )
        }
    }

    static func reassignSegment(id: Segment.ID, to label: String, in segments: [Segment]) -> [Segment] {
        guard let targetLabel = SpeakerLabel.normalized(label) else {
            return segments
        }

        return segments.map { segment in
            guard segment.id == id else {
                return segment
            }
            var updated = segment
            updated.speaker = targetLabel
            return updated
        }
    }

    static func nextNewSpeakerLabel(existing labels: [String]) -> String {
        let existingLabels = Set(labels.compactMap { SpeakerLabel.normalized($0) })
        var index = 1
        while existingLabels.contains("화자 \(index)") {
            index += 1
        }
        return "화자 \(index)"
    }
}
